services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-db
    restart: always
    ports:
      - "${HOST_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data 